### ISSUE TITLE
Froala Base64 images disappears on click

### ISSUE THREAD

**Issue by gaboOliveira** [wiris/html-integrations#740] opened 2022-12-22 16:40 UTC
## Description

Some base64 images are disappearing when we click on them

## Environment

We're using @wiris/mathtype-froala: ^8.1.0 and react-froala-wysiwyg: ^4.0.10

*What is the relevant software and their versions?*

- *Editor Froala
- *Framework React

## Steps to reproduce

*What are the steps needed to reproduce the bug?*

Once we open the page within the image 
`<img data-fr-image-pasted="true" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAApCAYAAAA4c3k5AAAAAXNSR0IArs4c6QAAALBJREFUSEvtlrENgzAQAI8ZGCJDkE1IJggNG7AGPRQZIX0Yhzol6CWTIAT4ZVlWEHb9Pv%2Bf%2FG8neFqJJw5BQRegAgqg36rAllEKtGZz7grKgLeBvAAn0AS5GdDdFTRXIZlE0P71jo48tb%2Bt19THnAQ0qIX8Ar9qTuLIQdGKLAtFJkBjYq5At4zXyJbn6Ak81gATMBho%2FiTJ4TVQAp%2FjlyYV%2FJfsmBFhv36qqaDptbCgEZeiNCqKPItyAAAAAElFTkSuQmCC" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;><mfrac><mn>1</mn><mi mathvariant=&quot;normal&quot;>f</mi></mfrac></math>" class="Wirisformula fr-fic fr-dii" role="math" alt="1 over straight f">` it shows up correctly but when we try to click it disappears. It happens to some base64 images but not all of them

## Expected result

*What is the expected outcome of the steps above?*

We should be able to click on the image without having it gone

## Actual result

*What is the actual outcome of the steps above?*

The image is gone on click event

## Other details

*Is there anything else to consider?*

After the click event, I can see that width and height attributes were added as 0, so, the image still there but is 'hide'.
Debugging the application, I was able to see that the setImgSize function is getting a non number size from the base64 image and then, the styling calc fails with non number results.
If I go to the DOM and remove the width and height attributes it shows up again but I'm still not able to click on it

![Screenshot 2022-12-22 163407](https://user-images.githubusercontent.com/15108656/209180863-f59a442b-e53b-40d9-b4c3-105dfc42e894.png)

then, after clicking on it

![Screenshot 2022-12-22 163941](https://user-images.githubusercontent.com/15108656/209181088-b95373d6-72b9-4ffb-8f32-ae66e9b74ac4.png)

**Comment by jguillen-at-wiris** [comment] 2023-05-10 08:36
Hi Gabo! Sorry for the late reply.

Thanks for reporting this issue.
We have dealing with similar cases and we will review if this is reproducible as of today.

We will be back to you with some feedback.
Should you still be experiencing this issue, please, make sure the package is updated, as our fixes are released in newer versions.

Thanks for your kind coooperation!

**Comment by xripoll-at-wiris** [comment] 2023-05-23 10:12
Hi @gaboOliveira !

I have been investigating this bug. I can indeed reproduce it, but I'm wondering how you got this formula, as it seems like the base64 encoding is not correct. When I try to initialize Froala with other formulas created by MathType, they seem to work correctly. Could you please walk me through the steps used to obtain this formula? And provide us any configuration that you're using for MathType (e.g. your configuration.ini if you are running your own MathType services in your backend).

Thank you!

**Comment by jguillen-at-wiris** [comment] 2023-06-08 07:47
Hi @gaboOliveira !

We will close this issue due to inactivity.
We could reproduce it but we found it has to do with the image encoding. Since we have no details to investigate what is the exact background that generated the image we can't proceed any further.

Please, should you need further assistance here, feel free to reopen this issue.

We hope you have a great day!

**Closed as completed by jguillen-at-wiris** 2023-06-08 07:47 UTC
Labels: type:bug
