### ISSUE TITLE
When any other dialog box in opened , when mathtype is already opened , either it should close or be underneath the dialog overlay

### ISSUE THREAD

**Issue by SIMRAN88** [wiris/html-integrations#134] opened 2020-11-26 04:58 UTC
Steps to reproduce the issue
1.Open wiris editor
2.Open image dialog box or preview box or media
3. The wiris editor comes on top of that.
Attaching images
![image](https://user-images.githubusercontent.com/12448024/100309864-dc8f9600-2fd1-11eb-82a7-d44e762c5c17.png)
![image](https://user-images.githubusercontent.com/12448024/100309903-f7faa100-2fd1-11eb-81b6-e4b88c50a356.png)
![image](https://user-images.githubusercontent.com/12448024/100309923-02b53600-2fd2-11eb-975a-89efbd1646df.png)

**Comment by carlawiris** [comment] 2020-11-26 09:49
Hi, Thank you for the report, we will add the issue in our list and work for it as soon as possible. 
But first we will need some more information: which editor are you using and on which browser is the bug happening.

**Comment by SIMRAN88** [comment] 2020-11-27 04:53
Hey @carlawiris. Thanks for your quick reply. We are using tinymce editor version 5.2.1. And we are testing in Chrome browser version 87.0.

**Comment by carlawiris** [comment] 2020-11-27 09:59
Great @SIMRAN88 ! We will add this information and let you know when we start working in the issue.

**Comment by SIMRAN88** [comment] 2021-02-23 07:35
Hi There, Any update on the issue?

**Comment by dcanet-at-wiris** [comment] 2021-08-25 12:17
Hi, @SIMRAN88 

First of all, sorry for the late answer.

We've been analyzing this issue thoroughty And our conclusion is that its more a feature request than a bug, itself.  

At the same time, we understand your situation and **we bring you a specific solution for this overlapping issue** with the different UI modal dialog windows implementations between core and third-party plugins on TinyMCE. 

In fact, we offer you three different options for you to choose. 🥳 

Let me explain myself, then. :)

## 01. The Problem

All TinyMCE plugins, both core and third-party, use HTML5 modal dialog windows to show their UI to the user.

This modal window allow developers to add dialogs to the HTML editor UX like for lightboxes, user notifications, forms or completely custom content.

While TinyMCE core plugins use their [own Dialog UI component](https://www.tiny.cloud/docs/ui-components/dialog/#dialogconfiguration), other third-party plugins, like MathType, use their own implementation and UX abstraction. 

These different implementations cause potential conflicts between the UI of some of the plugins activated on a TinyMCE editor instance. 

![conflict](https://user-images.githubusercontent.com/85346791/130788173-7376613c-77da-44dd-a0b7-76b87018ccb0.png)


## 02. How to mitigate this issue

These are some changes that can be considered in your project in order to mitigate and/or fix this issue. 
 
### A. Activate `draggable_modal` TinyMCE UI option

> Recommended solution.

There is a TinyMCE user interface configuration option that could help fix and/or mitigate this issue.

Setting the [`draggable_modal`](https://www.tiny.cloud/docs/configure/editor-appearance/#draggable_modal) option to `true` will enable dragging for any core plugin modal dialog: image, link, media, ....

Activating this will help users to share the screen viewport between TinyMCE and MathType modal windows without conflict.

[Reference](https://www.tiny.cloud/docs/configure/editor-appearance/#draggable_modal).

### B. Activate `wiriseditormodalwindowfullscreen` MathType UI option

The default behaviour of MathType allows the user to interact with the web page *under* the MathType dialog window.

This is considered a feature since a lot of web projects using MathType depend on this UX abstraction to keep their users' process.

At the same time, this behaviour can be changed using the `wiriseditormodalwindowfullscreen` parameter.

It can take work on two modes: `Normal` and `Maximized`. 

While the `Normal` mode allows the user to interact with the elements on the page, the `Maximized` mode.

![Normal mode](https://user-images.githubusercontent.com/85346791/130781825-5d8729f9-a321-41c8-a50b-b8aa97eef2f0.png)

By setting the [`wiriseditormodalwindowfullscreen`](https://docs.wiris.com/en/mathtype/mathtype_web/integrations/config-table) configuration setting to `true` the MathType Modal window will appear `Maximized`. This is the same default as the TinyMCE dialog modal windows.

This change will fix this issue since it will be impossible for the user to interact with the TinyMCE toolbar and, therefore, the issue can't be reproduced anymore.

![Maximized](https://user-images.githubusercontent.com/85346791/130781933-bcb32593-7878-4c3c-b4ed-06e29b0e6dbe.png)

[Reference](https://docs.wiris.com/en/mathtype/mathtype_web/integrations/config-table)

### C. A CSS fix on your application

Both Dialog UI component implementations, TinyMCE's and MathType's, use the `z-index` css property to control the modal windows visibility in terms of layer position.

While the TinyMCE sets the `z-index` value to 2, as defined by the CSS class `tox-dialog`.

```css
.tox .tox-dialog {
    ...
    z-index: 2;
}
```

MathType sets the `z-index` value of is modal dialog box to 99999.

Therefore, by changing this value the MathType window will appear *behind* any TinyMCE Modal dialog component and the issue won't be reproducible, either.   

![zindex fix](https://user-images.githubusercontent.com/85346791/130786525-ab6cf001-672f-4b94-b18c-b22cdba1fe70.png)

To do that, add this CSS directive to your project:

```css
.wrs_modal_dialogContainer {
    z-index: 2 !important   ;
}

```

That would be all..

Please, let me know if this information is helpful to you, so we could proceed to close the issue.

Again, many thanks for your patience.

Kind regards,

D.

**Comment by dcanet-at-wiris** [comment] 2021-08-31 06:55
Hola @SIMRAN88 

I proceed to close the issue.

Kind regards.

**Closed by dcanet-at-wiris** 2021-08-31 06:55 UTC
Labels: type:question, package:tinymce5, state:accepted, state:requested, browser:chrome
