### ISSUE TITLE
[CKEditor 5] Improve inline widget insertion

### ISSUE THREAD

**Issue by filipsobol** [wiris/html-integrations#811] opened 2023-05-23 10:22 UTC
## Description

While investigating the bug reported in https://github.com/ckeditor/ckeditor5/issues/14106, we noticed some issues with MathType integration. The issue described in the bug is fixed for inline widgets. To make it work for MathType, it needs to:

1. Change the schema registration from

    https://github.com/wiris/html-integrations/blob/29fd293e7a7dfaacd4daed0d26fe2b5efebc7c35/packages/ckeditor5/src/plugin.js#L201C17-L206

    to:

    ```js
    schema.register('mathml', {
      inheritAllFrom: '$inlineObject',
      allowAttributes: ['formula'],
    });
    ```
    
    For more details see https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/implementing-an-inline-widget.html#defining-the-schema.

2. Change the way you modify the model to insert the `<mathml>` element. Instead of using `writer.insert()` as shown below, use `model.insertObject()` instead.

    https://github.com/wiris/html-integrations/blob/29fd293e7a7dfaacd4daed0d26fe2b5efebc7c35/packages/ckeditor5/src/integration.js#L161

    https://github.com/wiris/html-integrations/blob/29fd293e7a7dfaacd4daed0d26fe2b5efebc7c35/packages/ckeditor5/src/integration.js#L183

    For more information see https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/implementing-an-inline-widget.html#command

## Environment

*Which version of MathType does this happen in?*

Latest

*What is the relevant software and their versions?*

CKEditor 5

## Steps to reproduce

1. Use the latest `@ckeditor/ckeditor5-engine` package from the CKEditor 5 repository (because the fix for the bug linked above has not yet been released).
2. Follow the reproduction steps in https://github.com/ckeditor/ckeditor5/issues/14106, but instead of using inline image, use mathml.

## Expected result

Text formatting is preserved after inserting the widget.

**Comment by jguillen-at-wiris** [comment] 2023-05-23 10:28
Hi Filip!
Thanks for reporting this issue and all the details provided.
We will open a case and review all that to make the necessary changes in our integration.

We will be back to you as soon as we have feedback from our side.

I hope you have a great day!

**Comment by mabryl** [comment] 2023-09-13 12:10
Hello Wiris support team!

I can see that the fix for this issue has been merged [here](https://github.com/wiris/html-integrations/pull/817) but we've received a report from one of our customers that the issue is still present in the MathType plugin for CKEditor 5.

I've just retested this in a fresh CKEditor build that contains the newest release of MathType and, indeed, it looks like the issue is still reproducible.

Take a look at the screenshot below to see that the font family is preserved when inserting an image but gets dropped once a math formula is inserted:

![image](https://github.com/wiris/html-integrations/assets/72079603/5b6a3da2-4083-468b-8edc-fb1aad991aa1)

Could you take another look at this issue?

**Comment by mabryl** [comment] 2023-09-13 12:16
The steps to reproduce look as follows:

1. Select some font property (non-default font name, bold, etc.) and type some text in the editor
2. Insert a MathType formula
3. Press spacebar
4. Continue typing

The expected result here is that the previously selected font properties are retained after inserting the formula.

The actual result is that these font properties are dropped and they go back to their default values set in the editor.

**Comment by xripoll-at-wiris** [comment] 2023-09-15 11:41
Hello @mabryl !

I could validate the behavior that you're reporting. I will create a task for my team to work on this, we will let you know once we have fixed this.

**Comment by xripoll-at-wiris** [comment] 2023-09-20 14:58
Hi @mabryl.

I've been studying this issue. Unfortunately I cannot reproduce the correct behavior even for images: when I insert an inline image, the font reverts back to the original. I am using version 39.0.0 of all CKEditor plugins, and I include the Font plugins as well as all the Image related plugins (as described in [this page](https://ckeditor.com/docs/ckeditor5/latest/features/images/images-installation.html)). Could you please link me to a demo or give me a snippet of how you're starting yours?

Thank you!

**Comment by mabryl** [comment] 2023-09-21 11:46
Hi @xripoll-at-wiris,

Thanks for the reply. You'll find a sample editor in the attachment to this message. To run it, navigate to the `wiris_sample/sample` directory and spin up a server there. I'm using the [http-sever utility](https://www.npmjs.com/package/http-server) for this purpose.

Once you access the editor, you'll see some predefined content there. The first paragraph contains some text with the _Courier New_ font applied to it, and an inline image inserted after the text. The text following the image retains the font and is also written in _Courier New_. The second paragraph also has text with the _Courier New_ font and a MathType widget inserted after the text. The text following the widget drops the font.

You should be able to reproduce this behavior using the steps outlined in my previous message.

The crucial thing here is that the widget inserted between the text has to be an _inline_ element, not a _block_ element. It's possible that you were inserting block images during your testing and that's why you couldn't reproduce the issue.

Let me know if you need anything else and thanks for your support.

[wiris_sample.zip](https://github.com/wiris/html-integrations/files/12684058/wiris_sample.zip)

**Comment by xripoll-at-wiris** [comment] 2023-09-22 10:54
Hi,

I could reproduce the bug correctly using the provided demo.

When I insert an image in my own demo, though, it is displayed inline (the text surrounds the image left and right), but it still removes the font afterwards.

> The crucial thing here is that the widget inserted between the text has to be an inline element, not a block element. It's possible that you were inserting block images during your testing and that's why you couldn't reproduce the issue.

We already register the element as inline:

```js
schema.register('mathml', {
  inheritAllFrom: '$inlineObject',
  allowAttributes: ['formula'],
});
```

and we insert using a plain `model.insertObject`. The behavior still persists; is there any other crucial point where we might be setting something wrong?

Thanks in advance

**Comment by mabryl** [comment] 2023-09-25 14:17
It's strange that you can't reproduce this issue in your own demo @xripoll-at-wiris. Could you let me know which version of the editor you're using?

Please keep in mind that a fix for this issue has been implemented in [v38.1.0](https://github.com/ckeditor/ckeditor5/releases/tag/v38.1.0) of CKEditor 5, so if your demo uses an older release, you won't see the results of the bugfix.

**Comment by mabryl** [comment] 2023-09-28 06:59
Thanks for the reply. So it looks like the version of the editor is not the cause of the issue here.

Would it be possible for you to share your current implementation? Perhaps there's some git branch that you could point us to see your code? Or maybe we could see a demo of your testing environment?

**Comment by xripoll-at-wiris** [comment] 2023-09-28 10:27
You can find a live demo in the following link: https://integrations.wiris.kitchen/KB-39091-demo/html/ckeditor5/

In order to deploy the same demo locally, clone the branch `KB-39091-demo` of [wiris/html-integrations](https://github.com/wiris/html-integrations), and then run the following commands:

```sh
yarn
yarn nx build ckeditor5
yarn nx start html-ckeditor5
```

And access the URL shown in the terminal.

The source code for the demo is in `demos/html/ckeditor5`, in particular take a look at `demos/html/ckeditor5/src/app.js` and `demos/html/ckeditor5/package.json`.

The source code of our integration for CKEditor 5 is in `packages/ckeditor5`, in particular check line 162 of `packages/ckeditor5/src/integration.js`.

**Comment by oleq** [comment] 2023-10-09 09:45
Hi, I checked your code and I think this fix should do the trick (based on the [core image feature implementation](https://github.com/ckeditor/ckeditor5/blob/3f1ca117225ec8d2787d1e6ba873da6a7827233d/packages/ckeditor5-image/src/imageutils.ts#L110-L117) of CKE5):

```diff
diff --git a/packages/ckeditor5/src/integration.js b/packages/ckeditor5/src/integration.js
index 7158a57d..37d44194 100644
--- a/packages/ckeditor5/src/integration.js
+++ b/packages/ckeditor5/src/integration.js
@@ -146,8 +146,13 @@ export default class CKEditor5Integration extends IntegrationModel {
     // This returns the value returned by the callback function (writer => {...})
     return this.editorObject.model.change((writer) => {
       const core = this.getCore();
+      const selection = this.editorObject.model.document.selection;
+
+      const modelElementNew = writer.createElement('mathml', {
+        formula: mathml,
+        ...Object.fromEntries( selection.getAttributes() )
+      });
 ```

https://github.com/wiris/html-integrations/assets/1099479/3ac22881-3905-48d5-8383-4b169868359e

**Comment by xripoll-at-wiris** [comment] 2023-10-10 10:28
Hello @oleq 

Thanks a lot for the fix. I just tested it and it seems to work great. I will submit it for our release cycle and we will publish it with our next version.

And thanks again to @mabryl for his involvement!

**Closed** 2023-12-01 10:51 UTC
Labels: type:bug
